apiVersion: apps/v1

kind: Deployment

metadata:
  name: lobo-codes

spec:
  replicas: 3
  selector:
    matchLabels:
      app: lobo-codes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lobo-codes
    spec:
      containers:
        - name: lobo-codes
          image: localhost:32000/lobo-codes:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OTLP_SERVER
              value: jaeger-cassandra-collector
            - name: EXPORTER
              value: otlp-grpc
            - name: CASSANDRA_SERVER
              value: cassandra-internal
            - name: HTTP_PORT
              value: "80"
            - name: HTTPS_PORT
              value: "443"
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https

