# Test config; see K8s deployment yaml for prod config

# Server config
HTTP_PORT: 3000
HTTPS_PORT: 3001

# Exporter
EXPORTER: otlp

# Jaeger endpoint
JAEGER_SERVER: localhost
JAEGER_PORT: 14268
JAEGER_PATH: /api/traces

# Zipkin endpoint
ZIPKIN_ENDPOINT: http://localhost:9411/api/v2/spans

# OTLP endpoint
OTLP_SERVER: localhost
OTLP_GRPC_PORT: 4317
OTLP_HTTP_PORT: 4318
OTLP_URL: /v1/traces

# Cassandra
CASSANDRA_SERVER: 10.1.1.42
CASSANDRA_RETRY: 2
CASSANDRA_SLEEP: 2

# Rqlite
RQLITE_HOST: 10.1.1.44
RQLITE_PORT: 4001
